[tool.towncrier]
package = "trio_monitor"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/python-trio/trio-monitor/issues/{issue}>`__"

[tool.pytest.ini_options]
faulthandler_timeout = 60
xfail_strict = true
trio_mode = true
